name: "EpsilonLink"
version: ${pluginVersion}
author: "EliXorZz"
main: fr.epsilon.bukkit.EpsilonLink

commands:
  joinqueue:
    description: "Rejoindre Queue"
  leavequeue:
    description: "Leave Queue"